[package]
name = "rshtein"
version = "0.1.0"
edition = "2018"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.bench]
codegen-units = 1
lto = true

[dependencies]
arrayvec = "0.5.1"
unchecked-index = "0.2.2"
